import textwrap

import pytest
import yaml
from wizard import PINECONE_VERSION, upgrade_project

STACK = "cell"
PROJECT = "pc"

# everything a deployed project holds that an upgrade has no business rewriting:
# the encrypted key, an adopted VPC and its subnets, tags, the control plane, and
# the top-level backend metadata that makes the encrypted value decryptable
CONFIG = {
    "aws:region": "us-east-2",
    f"{PROJECT}:region": "us-east-2",
    f"{PROJECT}:pinecone-version": "main-0000000",
    f"{PROJECT}:availability-zones": ["us-east-2a", "us-east-2b"],
    f"{PROJECT}:existing-vpc-id": "vpc-0abc",
    f"{PROJECT}:private-subnet-ids": ["subnet-1", "subnet-2"],
    f"{PROJECT}:public-subnet-ids": ["subnet-3"],
    f"{PROJECT}:domain": "cells.example.com",
    f"{PROJECT}:public-access-enabled": False,
    f"{PROJECT}:deletion-protection": True,
    f"{PROJECT}:global-env": "ci",
    f"{PROJECT}:tags": {"owner": "ilia"},
    f"{PROJECT}:pinecone-api-key": {"secure": "v1:cipher=="},
}

DEPLOYED = {
    "encryptionsalt": "v1:c2FsdA==:v1:salt:cipher==",
    "secretsprovider": "passphrase",
    "config": CONFIG,
}


@pytest.fixture
def deployed(tmp_path):
    (tmp_path / "Pulumi.yaml").write_text(f"name: {PROJECT}\nruntime: python\n")
    (tmp_path / "__main__.py").write_text(
        textwrap.dedent("""\
            import pulumi
            from pulumi_pinecone_byoc.aws import PineconeAWSCluster, PineconeAWSClusterArgs
            # generated by an older wizard
            """)
    )
    (tmp_path / "pyproject.toml").write_text(
        '[project]\ndependencies = ["pulumi-pinecone-byoc[aws]"]\n'
    )
    (tmp_path / f"Pulumi.{STACK}.yaml").write_text(yaml.safe_dump(DEPLOYED, sort_keys=True))
    return tmp_path


def stack_file(project_dir):
    return yaml.safe_load((project_dir / f"Pulumi.{STACK}.yaml").read_text())


def test_an_upgrade_answers_nothing_and_touches_no_credentials(deployed, monkeypatch):
    """The answers are already in the stack file, so the wizard is not run again.

    A regenerating upgrade would validate an API key it does not have, preflight
    for room to create a cluster that exists, and ask which backend to use.
    """
    monkeypatch.setattr(
        "wizard.AWSSetupWizard._validate_api_key",
        lambda self, key: pytest.fail("an upgrade has no key to validate"),
    )
    monkeypatch.setattr(
        "wizard.AWSSetupWizard._run_preflight_checks",
        lambda self, *a, **k: pytest.fail("an upgrade preflights nothing"),
    )
    monkeypatch.setattr(
        "wizard.AWSSetupWizard._setup_pulumi_backend",
        lambda self: pytest.fail("an upgrade does not choose a backend"),
    )

    assert upgrade_project(str(deployed), STACK, None)


def test_the_program_is_rewritten_for_this_version(deployed):
    assert upgrade_project(str(deployed), STACK, None)

    program = (deployed / "__main__.py").read_text()
    assert "generated by an older wizard" not in program
    assert "PineconeAWSClusterArgs(" in program
    assert "control_plane = {" in program


def test_only_the_pinecone_version_moves(deployed):
    assert upgrade_project(str(deployed), STACK, None)

    after = stack_file(deployed)
    assert after["config"][f"{PROJECT}:pinecone-version"] == PINECONE_VERSION

    expected = dict(CONFIG)
    expected[f"{PROJECT}:pinecone-version"] = PINECONE_VERSION
    assert after["config"] == expected


def test_the_backend_metadata_outlives_the_upgrade(deployed):
    """A carried-over `secure` value is undecryptable without the salt beside it."""
    assert upgrade_project(str(deployed), STACK, None)

    after = stack_file(deployed)
    assert after["encryptionsalt"] == "v1:c2FsdA==:v1:salt:cipher=="
    assert after["secretsprovider"] == "passphrase"
    assert after["config"][f"{PROJECT}:pinecone-api-key"] == {"secure": "v1:cipher=="}


def test_the_equals_form_of_the_stack_name_is_a_stack_name(deployed):
    """argparse accepts --stack-name=cell, and the upgrade has to read it as given."""
    import wizard

    assert wizard._find_stack(str(deployed), STACK) == STACK


def test_a_project_the_wizard_did_not_generate_is_refused(tmp_path):
    (tmp_path / "Pulumi.yaml").write_text(f"name: {PROJECT}\nruntime: python\n")
    assert not upgrade_project(str(tmp_path), STACK, None)


def test_a_clone_url_with_a_token_in_it_is_never_written_into_a_project():
    from wizard import _https_remote

    assert _https_remote("git@github.com:pinecone-io/pulumi-pinecone-byoc.git") == (
        "https://github.com/pinecone-io/pulumi-pinecone-byoc"
    )
    assert _https_remote("ssh://git@github.com/pinecone-io/pulumi-pinecone-byoc.git") == (
        "https://github.com/pinecone-io/pulumi-pinecone-byoc"
    )
    assert _https_remote("https://github.com/pinecone-io/pulumi-pinecone-byoc") == (
        "https://github.com/pinecone-io/pulumi-pinecone-byoc"
    )
    # assembled rather than written out: a literal user:password@host is a basic-auth
    # string to a secret scanner, which then blocks the push over a fabricated one
    host = "@github.com/pinecone-io/pulumi-pinecone-byoc"
    for credentialed in (
        f"https://x-access-token:{'ghp_' + 'secretvalue'}{host}.git",
        f"https://ilia:{'hunter' + '2'}{host}",
    ):
        stripped = _https_remote(credentialed)
        assert stripped == "https://github.com/pinecone-io/pulumi-pinecone-byoc"
        assert "@" not in stripped
        assert "secretvalue" not in stripped and "hunter2" not in stripped


def test_the_pinned_rev_is_read_back_out_of_a_generated_pyproject(tmp_path):
    from wizard import pinned_rev

    path = tmp_path / "pyproject.toml"
    path.write_text(
        '[project]\ndependencies = ["pulumi-pinecone-byoc[aws]"]\n\n'
        "[tool.uv.sources]\n"
        'pulumi-pinecone-byoc = { git = "https://github.com/pinecone-io/pulumi-pinecone-byoc",'
        ' rev = "94a9e90aa1b2c3d4e5f60718293a4b5c6d7e8f90" }\n'
    )
    assert pinned_rev(str(path)) == "94a9e90aa1b2c3d4e5f60718293a4b5c6d7e8f90"
    assert pinned_rev(str(tmp_path / "nothing-here.toml")) is None
