"""Helpers for driving the byovpc fixture and generated BYOC projects."""

import getpass
import json
import os
import shutil
import subprocess
import tempfile
import threading
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_DIR = REPO_ROOT / "tests" / "fixtures" / "byovpc"
ELB_TAG = "kubernetes.io/role/elb"
INTERNAL_ELB_TAG = "kubernetes.io/role/internal-elb"

_LOG = {"path": Path(os.environ.get("BYOVPC_LOG") or REPO_ROOT / "byovpc-test.log")}


def log_path():
    return _LOG["path"]


def set_log_path(path):
    """Point the run log at a per-session file so concurrent runs cannot interleave."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    _LOG["path"] = path
    return path


def log_dir():
    """Where per-pod logs are written; defaults to the run log's directory."""
    return Path(os.environ.get("BYOVPC_LOG_DIR") or log_path().parent)


def _stamp():
    return datetime.now().strftime("%H:%M:%S")


def log_line(text=""):
    """Append to the run log so a completed run can be inspected after the fact."""
    with log_path().open("a") as handle:
        handle.write(f"{_stamp()} {text}\n" if text else "\n")


def run(*args, cwd, env=None):
    """Run a command, echoing output live (visible with -s), keeping a copy so
    failures carry the reason, and teeing everything to LOG_PATH."""
    print(f"\n$ {' '.join(args)}  [{cwd}]", flush=True)
    log_line(f"$ {' '.join(args)}  [{cwd}]")
    proc = subprocess.Popen(
        args,
        cwd=cwd,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        bufsize=1,
        env={**os.environ, **(env or {})},
    )
    lines = []
    with log_path().open("a") as log:
        for line in proc.stdout:
            lines.append(line)
            print(line, end="", flush=True)
            log.write(f"{_stamp()} {line}")
            log.flush()
    proc.wait()
    output = "".join(lines)
    log_line(f"-> exit {proc.returncode}")
    if proc.returncode != 0:
        raise AssertionError(
            f"`{' '.join(args)}` failed with exit {proc.returncode} in {cwd}\n"
            f"{output.strip() or '(no output)'}"
        )
    return output


def pulumi(*args, cwd=FIXTURE_DIR, env=None):
    return run("pulumi", *args, cwd=cwd, env=env)


def pulumi_release(*args, cwd=FIXTURE_DIR):
    """Best-effort pulumi call for teardown steps that must not fail a run:
    cancelling a stale lock, removing an already-destroyed stack."""
    result = subprocess.run(["pulumi", *args], cwd=cwd, text=True, capture_output=True, check=False)
    log_line(f"$ pulumi {' '.join(args)} -> exit {result.returncode}")
    return result.returncode == 0


def destroy_stack(cwd, stack=None):
    """Destroy and then remove a stack, the way the CI workflow does: a run that was
    killed mid-update leaves a lock behind, and a leftover stack name blocks reuse."""
    scoped = (["--stack", stack] if stack else []) + ["--yes"]
    pulumi_release("cancel", *scoped, cwd=cwd)
    pulumi("destroy", "--yes", "--skip-preview", *(["--stack", stack] if stack else []), cwd=cwd)
    pulumi_release(
        "stack", "rm", *(["--stack", stack] if stack else []), "--yes", "--force", cwd=cwd
    )


def pulumi_json(*args, cwd=FIXTURE_DIR):
    result = subprocess.run(["pulumi", *args], cwd=cwd, text=True, capture_output=True, check=False)
    if result.returncode != 0:
        raise AssertionError(
            f"`pulumi {' '.join(args)}` failed with exit {result.returncode}\n"
            f"{(result.stderr or result.stdout or '').strip()}"
        )
    return json.loads(result.stdout)


def stack_name(*parts):
    """Stack names are per-developer by default; CI sets BYOVPC_STACK_PREFIX so
    concurrent pull requests never share a stack."""
    prefix = os.environ.get("BYOVPC_STACK_PREFIX") or os.environ.get("USER") or getpass.getuser()
    return "-".join([prefix, *parts])


def tags(resource):
    return {t["Key"]: t["Value"] for t in resource.get("Tags", [])}


INDEX_API_VERSION = os.environ.get("PINECONE_API_VERSION", "2025-04")


def project_credentials(project_dir):
    """Read the BYOC project's own api key and api url out of the stack state.

    The pc-api-key resource stores them in its outputs, so teardown can talk to
    the project it created rather than to whatever PINECONE_API_KEY happens to
    be exported in the shell.
    """
    exported = subprocess.run(
        ["pulumi", "stack", "export", "--show-secrets"],
        cwd=project_dir,
        capture_output=True,
        text=True,
        check=False,
    )
    if exported.returncode != 0:
        log_line(f"[cleanup] stack export failed: {(exported.stderr or '').strip()[:200]}")
        return None, None
    try:
        deployment = json.loads(exported.stdout).get("deployment", {})
    except ValueError as exc:
        log_line(f"[cleanup] could not parse stack export: {exc}")
        return None, None
    for resource in deployment.get("resources", []):
        if "pc-api-key" not in resource.get("urn", ""):
            continue
        outputs = resource.get("outputs", {})
        return outputs.get("value"), outputs.get("api_url")
    return None, None


def _list_indexes(requests, api_url, headers):
    listed = requests.get(f"{api_url}/indexes", headers=headers, timeout=30)
    if listed.status_code != 200:
        log_line(f"[cleanup] listing indexes returned {listed.status_code}: {listed.text[:200]}")
        return None
    return [index["name"] for index in listed.json().get("indexes", [])]


def delete_project_indexes(project_dir, timeout_seconds=600, poll_seconds=15):
    """Delete indexes left behind in the BYOC project before destroying it.

    A failed install leaves the SLI checker's index behind, and the management
    plane refuses to delete a project that still holds indexes (412), which
    blocks teardown permanently.

    Deletion is asynchronous (the API answers 202), so this waits for the
    indexes to actually disappear before returning - otherwise the destroy that
    follows still sees them. Best effort: never raises.
    """
    try:
        import time

        import requests

        api_key, api_url = project_credentials(project_dir)
        if not api_key or not api_url:
            log_line("[cleanup] no project api key in state, skipping index cleanup")
            return
        headers = {"Api-Key": api_key, "X-Pinecone-Api-Version": INDEX_API_VERSION}

        names = _list_indexes(requests, api_url, headers)
        if names is None:
            return
        if not names:
            log_line("[cleanup] project has no leftover indexes")
            return

        log_line(f"[cleanup] deleting leftover indexes: {', '.join(names)}")
        for name in names:
            deleted = requests.delete(f"{api_url}/indexes/{name}", headers=headers, timeout=120)
            log_line(f"[cleanup] delete index {name} -> {deleted.status_code}")

        deadline = time.time() + timeout_seconds
        while time.time() < deadline:
            remaining = _list_indexes(requests, api_url, headers)
            if remaining is None:
                return
            if not remaining:
                log_line("[cleanup] all indexes deleted")
                return
            log_line(f"[cleanup] waiting for index deletion: {', '.join(remaining)}")
            time.sleep(poll_seconds)
        log_line(
            f"[cleanup] indexes still present after {timeout_seconds}s - "
            "project deletion will fail with 412"
        )
    except Exception as exc:  # noqa: BLE001 - cleanup must never fail the teardown
        log_line(f"[cleanup] index cleanup failed: {type(exc).__name__}: {exc}")


def list_clusters(region):
    import boto3

    return set(boto3.client("eks", region_name=region).list_clusters()["clusters"])


def _find_cluster_for_vpc(vpc_id, region, baseline=None):
    """Locate this run's EKS cluster.

    With a vpc_id (BYO-VPC) the cluster is matched by the VPC it sits in. For a
    vanilla deploy the VPC is created by the module and unknown up front, so any
    cluster that did not exist when the run started is ours.
    """
    import boto3

    eks = boto3.client("eks", region_name=region)
    for name in eks.list_clusters()["clusters"]:
        if vpc_id is None and baseline is not None and name in baseline:
            continue
        try:
            cluster = eks.describe_cluster(name=name)["cluster"]
        except Exception:  # noqa: BLE001 - a prior run's cluster can vanish mid-listing
            continue
        if vpc_id is None or cluster.get("resourcesVpcConfig", {}).get("vpcId") == vpc_id:
            return name, cluster.get("status")
    return None, None


_STATUS = {"cluster": None, "pods": 0, "restarts": 0}


def _heartbeat(stop_event, seconds):
    while not stop_event.wait(seconds):
        log_line(
            f"[pinetools] watchdog alive - cluster={_STATUS['cluster']} "
            f"pods_followed={_STATUS['pods']} restarts={_STATUS['restarts']}"
        )


def supervise_pinetools_logs(vpc_id, stop_event, poll_seconds=15, heartbeat_seconds=300):
    """Watchdog around the log streamer.

    The streamer must survive the whole deploy; if it ever returns or raises it
    is restarted, so a single transient failure cannot leave the run unobserved.
    """
    if not shutil.which("kubectl"):
        log_line("[pinetools] kubectl not on PATH - installer logs will NOT be captured")
        return

    threading.Thread(target=_heartbeat, args=(stop_event, heartbeat_seconds), daemon=True).start()

    while not stop_event.is_set():
        try:
            stream_pinetools_logs(vpc_id, stop_event, poll_seconds)
        except BaseException as exc:  # noqa: BLE001 - the watchdog outlives any failure
            log_line(f"[pinetools] streamer crashed: {type(exc).__name__}: {exc}")
        if stop_event.is_set():
            break
        _STATUS["restarts"] += 1
        log_line(f"[pinetools] restarting streamer (restart #{_STATUS['restarts']})")
        stop_event.wait(5)
    log_line("[pinetools] watchdog stopped")


UNHEALTHY_WAITING = {
    "CrashLoopBackOff",
    "ImagePullBackOff",
    "ErrImagePull",
    "CreateContainerConfigError",
    "CreateContainerError",
}


def _kubectl_all(kubeconfig, *args, timeout=60):
    """kubectl without pinning a namespace."""
    return subprocess.run(
        ["kubectl", "--kubeconfig", kubeconfig, *args],
        capture_output=True,
        text=True,
        check=False,
        timeout=timeout,
    )


def _unhealthy_pods(kubeconfig):
    """Pods stuck in a crash/pull loop anywhere in the cluster."""
    listed = _kubectl_all(kubeconfig, "get", "pods", "-A", "-o", "json")
    if listed.returncode != 0:
        return []
    try:
        items = json.loads(listed.stdout).get("items", [])
    except ValueError:
        return []
    found = []
    for pod in items:
        meta = pod.get("metadata", {})
        status = pod.get("status", {})
        statuses = status.get("containerStatuses") or []

        # an unschedulable pod never gets containerStatuses, so it has to be
        # detected from the Pending phase and its scheduling condition
        if status.get("phase") == "Pending" and not statuses:
            unschedulable = any(
                c.get("type") == "PodScheduled" and c.get("status") == "False"
                for c in status.get("conditions") or []
            )
            if unschedulable:
                found.append((meta.get("namespace"), meta.get("name"), "Unschedulable"))
            continue

        for container in statuses:
            reason = (container.get("state", {}).get("waiting") or {}).get("reason")
            if reason in UNHEALTHY_WAITING or container.get("restartCount", 0) >= 3:
                found.append((meta.get("namespace"), meta.get("name"), reason or "restarting"))
                break
    return found


def capture_unhealthy_pod(kubeconfig, namespace, pod, reason):
    """Save why a pod is failing, while the cluster still exists.

    The previous container's logs are the useful part: a crash-looping pod's
    current instance is usually too young to have logged the failure, and all of
    it disappears when the cluster is torn down.
    """
    target = log_dir() / f"crashloop-{namespace}-{pod}.log"
    log_line(f"[crashloop] {namespace}/{pod} {reason} -> {target}")
    print(f"[crashloop] {namespace}/{pod} {reason} -> {target}", flush=True)
    with target.open("a") as handle:
        handle.write(f"===== {namespace}/{pod} reason={reason} =====\n")
        for label, args in (
            (
                "previous logs",
                [
                    "logs",
                    pod,
                    "-n",
                    namespace,
                    "--all-containers=true",
                    "--prefix",
                    "--previous",
                    "--tail",
                    "400",
                ],
            ),
            (
                "current logs",
                [
                    "logs",
                    pod,
                    "-n",
                    namespace,
                    "--all-containers=true",
                    "--prefix",
                    "--tail",
                    "400",
                ],
            ),
            ("describe", ["describe", "pod", pod, "-n", namespace]),
        ):
            result = _kubectl_all(kubeconfig, *args, timeout=90)
            handle.write(f"\n----- {label} (exit {result.returncode}) -----\n")
            handle.write(result.stdout or result.stderr or "(nothing)")
            handle.flush()


def _kubectl(kubeconfig, *args, timeout=60):
    return subprocess.run(
        ["kubectl", "--kubeconfig", kubeconfig, "-n", "pc-control-plane", *args],
        capture_output=True,
        text=True,
        check=False,
        timeout=timeout,
    )


def _ensure_kubeconfig(vpc_id, region, stop_event, poll_seconds, baseline=None):
    """Keep trying until the cluster exists and a kubeconfig is written."""
    while not stop_event.is_set():
        try:
            name, status = _find_cluster_for_vpc(vpc_id, region, baseline)
            if name and status == "ACTIVE":
                path = str(Path(tempfile.mkdtemp()) / "kubeconfig")
                written = subprocess.run(
                    [
                        "aws",
                        "eks",
                        "update-kubeconfig",
                        "--name",
                        name,
                        "--region",
                        region,
                        "--kubeconfig",
                        path,
                    ],
                    capture_output=True,
                    text=True,
                    check=False,
                )
                if written.returncode == 0:
                    log_line(f"[pinetools] streaming logs from cluster {name}")
                    _STATUS["cluster"] = name
                    return path
                log_line(
                    f"[pinetools] update-kubeconfig failed, retrying: {written.stderr.strip()[:200]}"
                )
        except Exception as exc:  # noqa: BLE001 - keep polling through transient AWS errors
            log_line(f"[pinetools] cluster lookup retrying: {type(exc).__name__}: {exc}")
        stop_event.wait(poll_seconds)
    return None


def _follow_pod(kubeconfig, pod, stop_event):
    """Attach to one pod, reattaching until it reaches a terminal phase.

    A pod spends minutes in PodInitializing (wait-for-regcred), where `kubectl
    logs -f` exits immediately, so a single attempt captures nothing.
    """
    pod_log = log_dir() / f"pinetools-{pod}.log"
    message = f"[pinetools] following {pod} -> {pod_log}"
    print(message, flush=True)
    log_line(message)

    captured_any = False
    with pod_log.open("a") as handle:
        while not stop_event.is_set():
            phase = ""
            got_output = False
            try:
                probe = _kubectl(kubeconfig, "get", "pod", pod, "-o", "jsonpath={.status.phase}")
                if probe.returncode != 0:
                    # the pod is gone (a superseded attempt, or job TTL); retrying
                    # would spam NotFound until the run ends
                    log_line(f"[pinetools] {pod} no longer exists, stopping follow")
                    break
                phase = probe.stdout.strip()
                # once something has been captured, only take new lines so a dropped
                # connection cannot duplicate the whole install log
                history = ["--tail", "0"] if captured_any else ["--since", "3h"]
                proc = subprocess.Popen(
                    [
                        "kubectl",
                        "--kubeconfig",
                        kubeconfig,
                        "-n",
                        "pc-control-plane",
                        "logs",
                        "-f",
                        pod,
                        "--all-containers=true",
                        "--prefix",
                        *history,
                    ],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                    bufsize=1,
                )
                for line in proc.stdout:
                    got_output = True
                    print(f"[{pod}] {line.rstrip()}", flush=True)
                    handle.write(f"{_stamp()} {line}")
                    handle.flush()
                proc.wait()
            except Exception as exc:  # noqa: BLE001 - reattach on any failure
                log_line(f"[pinetools] {pod} attach retrying: {type(exc).__name__}: {exc}")
            if got_output and proc.returncode == 0:
                captured_any = True
            if phase in ("Succeeded", "Failed"):
                break
            if stop_event.wait(5):
                break

        try:
            handle.write("\n===== kubectl describe pod =====\n")
            handle.write(_kubectl(kubeconfig, "describe", "pod", pod).stdout)
            handle.flush()
        except Exception:  # noqa: BLE001
            pass
    log_line(f"[pinetools] {pod} finished -> {pod_log}")


def stream_pinetools_logs(vpc_id, stop_event, poll_seconds=15):
    """Follow pinetools install/uninstall pod logs for the whole deploy.

    Every layer retries: a transient AWS error, a missing cluster or a pod that
    is not ready yet must never end the stream.
    """
    if not shutil.which("kubectl"):
        log_line("[pinetools] kubectl not on PATH - installer logs will NOT be captured")
        return

    region = os.environ["AWS_REGION"]
    baseline = None
    if vpc_id is None:
        try:
            baseline = list_clusters(region)
            log_line(f"[pinetools] vanilla run; ignoring pre-existing clusters: {sorted(baseline)}")
        except Exception as exc:  # noqa: BLE001
            log_line(f"[pinetools] could not snapshot clusters: {type(exc).__name__}: {exc}")
    kubeconfig = _ensure_kubeconfig(vpc_id, region, stop_event, poll_seconds, baseline)
    if kubeconfig is None:
        return

    followed = {}
    captured_unhealthy = set()
    while not stop_event.is_set():
        try:
            listed = _kubectl(kubeconfig, "get", "pods", "-o", "name")
            for line in listed.stdout.splitlines():
                pod = line.removeprefix("pod/").strip()
                if not pod.startswith("pinetools-") or pod in followed:
                    continue
                worker = threading.Thread(
                    target=_follow_pod, args=(kubeconfig, pod, stop_event), daemon=True
                )
                worker.start()
                followed[pod] = worker
                _STATUS["pods"] = len(followed)
        except Exception as exc:  # noqa: BLE001 - keep polling for new pods
            log_line(f"[pinetools] pod poll retrying: {type(exc).__name__}: {exc}")

        try:
            for namespace, pod, reason in _unhealthy_pods(kubeconfig):
                if (namespace, pod) in captured_unhealthy:
                    continue
                captured_unhealthy.add((namespace, pod))
                capture_unhealthy_pod(kubeconfig, namespace, pod, reason)
        except Exception as exc:  # noqa: BLE001 - diagnostics must not stop the stream
            log_line(f"[crashloop] scan retrying: {type(exc).__name__}: {exc}")

        stop_event.wait(poll_seconds)


def parse_wizard_env(wizard_env):
    return dict(
        line.removeprefix("export ").split("=", 1)
        for line in wizard_env.splitlines()
        if line.startswith("export ")
    )
